spring:
  application:
    #服务名称
    name: smart-community-wechat

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
#  data:
#    elasticsearch:
#      repositories:
#        enabled: true
#      cluster-nodes: 192.168.8.14:9300 # es的连接地址及端口号
  #数据库连接池配置
  datasource:
    master:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.133.50:3306/scaffold?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
      username: root
      password: 123456
  #    cluster:
  #      - key: slave1
  #        type: com.zaxxer.hikari.HikariDataSource
  #        driver-class-name: com.mysql.cj.jdbc.Driver
  #        url: jdbc:mysql://mysql.tftnet.com:3306/smart_community?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
  #        username: root
  #        password: tftnet
  #      - key: slave2
  #        type: com.zaxxer.hikari.HikariDataSource
  #        driver-class-name: com.mysql.cj.jdbc.Driver
  #        url: jdbc:mysql://mysql.tftnet.com:3306/smart_community?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
  #        username: root
  #        password: tftnet

  redis:
    host: 192.168.133.50
    port: 6379
    lettuce:
      pool:
        # 最大连接数 默认8
        max-active: 8
        # 最大空闲连接数 默认8
        max-idle: 8
        # 最小空闲连接数 默认0
        min-idle: 0
    password: 123456
server:
  port: 999
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /smart-community-wechat

# MyBatis config
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml,mapper/*.xml,/mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: STATUS
      logic-delete-value: -1 # 逻辑已删除值
      logic-not-delete-value: 1 # 逻辑未删除值
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#   配置pagehelper参数
pagehelper:
  # 允许在运行时根据多数据源自动识别对应方言的分页 不支持SqlServer2012
  autoRuntimeDialect: true
  # 分页合理化参数 pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页
  reasonable: true
  # 自动关闭数据库连接
  closeConn: true
#  helper-dialect: mysql

# Swagger开关配置   可在生产环境关闭Swagger
swagger2:
  enable: true

#最大连接数
http.maxTotal: 100
#并发数
http.defaultMaxPerRoute: 20
#创建连接的最长时间
http.connectTimeout: 3000
#从连接池中获取到连接的最长时间
http.connectionRequestTimeout: 500
#数据传输的最长时间
http.socketTimeout: 100000
#提交请求前测试连接是否可用
http.staleConnectionCheckEnabled: true

file:
  path: E:\项目文档\保税区智慧社区\原型
  template:
    base: /data/var/upload/smartcommunity/template/
    certification: certificationTemplate
nginx:
  file:
    server: http://192.168.24.116:8094/file/

#token过期时间
atToken:
  expireSeconds: 3600

